version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - spring-mongo
      -
  rabbitmq:
    image: rabbitmq:3.9.8-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - spring-mongo

  transferenciassa:
    image: transferenciassa
    restart: always
    build: .
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=admin123
      - SPRING_DATA_MONGODB_DATABASE=transferenciassa_db
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - 8082:8080
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - spring-mongo

volumes:
  mongo-data:
  rabbitmq-data:

networks:
  spring-mongo:
    driver: bridge
