version: '3.9'


services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - spring-mongo

  rabbitmq:
    image: rabbitmq:3.9.8-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - spring-mongo

  CenterSA:
    build: .
    image: centersa:latest
    restart: always
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: admin123
      SPRING_DATA_MONGODB_DATABASE: record_db
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - 8086:8090
    expose:
      - 8090
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - spring-mongo

volumes:
  mongo-data:
  rabbitmq-data:

networks:
  spring-mongo:
    driver: bridge
